stages:
  - build
  - test
  - deploy
  - status

.run_only_if_file_changed_template:
  only:
    refs:
      - merge_requests
    changes:
      - maintainer/docker_build.sh
      - maintainer/generate.sh
      - docker/${${CI_JOB_NAME%:build}%:*}/Dockerfile-${${CI_JOB_NAME%:build}#*:}

.build_template:
  extends: .run_only_if_file_changed_template
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - sh maintainer/docker_build.sh
  tags:
    - docker
    - linux
    - nofirewall

.deploy_template:
  extends: .build_template
  stage: deploy
  only:
    - master

.test_template:
  extends: .run_only_if_file_changed_template
  stage: test
  image: $CI_REGISTRY/$CI_PROJECT_PATH/$CI_JOB_NAME-$CI_COMMIT_SHA
  script:
    - git clone --depth=1 --recursive https://github.com/espressomd/espresso
    - cd espresso
    - maintainer/CI/build_cmake.sh
  variables:
    make_check: "false"
    myconfig: "maxset"
  tags:
    - docker
    - linux

.test_template_v40:
  extends: .test_template
  script:
    - git clone -b 4.0 --depth=1 --recursive https://github.com/espressomd/espresso
    - cd espresso
    - maintainer/CI/build_cmake.sh

.test_py3_template:
  extends: .test_template
  variables:
    python_version: "3"

centos:7:build:
  extends: .build_template
centos-python3:7:build:
  extends: .build_template
centos:next:build:
  extends: .build_template
centos-python3:next:build:
  extends: .build_template
debian:9:build:
  extends: .build_template
opensuse:42.3:build:
  extends: .build_template
opensuse:15.0:build:
  extends: .build_template
opensuse:15.1:build:
  extends: .build_template
ubuntu:16.04:build:
  extends: .build_template
ubuntu:summerschool:build:
  extends: .build_template
ubuntu:18.04:build:
  extends: .build_template
ubuntu:wo-dependencies:build:
  extends: .build_template
clang:6.0:build:
  extends: .build_template
cuda:tutorials:build:
  extends: .build_template
cuda:9.0:build:
  extends: .build_template
rocm:latest:build:
  extends: .build_template
intel:15:build:
  extends: .build_template
  tags:
    - docker
    - linux
    - nofirewall
    - icp
intel:18:build:
  extends: .build_template
  tags:
    - docker
    - linux
    - nofirewall
    - icp
ubuntu-python3:16.04:build:
  extends: .build_template
ubuntu-python3:18.04:build:
  extends: .build_template
ubuntu-python3:min_boost:build:
  extends: .build_template
ubuntu:arm64:build:
  extends: .build_template
ubuntu:armhf:build:
  extends: .build_template
ubuntu:i386:build:
  extends: .build_template
ubuntu:ppc64le:build:
  extends: .build_template
ubuntu:s390x:build:
  extends: .build_template

test/centos:7:
  extends: .test_template_v40
test/centos-python3:7:
  extends: .test_py3_template
test/centos:next:
  extends: .test_template_v40
test/centos-python3:next:
  extends: .test_py3_template
test/debian:9:
  extends: .test_template
test/opensuse:42.3:
  extends: .test_template_v40
test/opensuse:15.0:
  extends: .test_template_v40
test/opensuse:15.1:
  extends: .test_py3_template
test/ubuntu:16.04:
  extends: .test_template
test/ubuntu:18.04:
  extends: .test_template
test/clang:6.0:
  extends: .test_template
test/cuda:tutorials:
  extends: .test_py3_template
test/cuda:9.0:
  extends: .test_py3_template
test/rocm:latest:
  extends: .test_template
  variables:
    make_check: "false"
    myconfig: "maxset"
    HIP_PLATFORM: "hcc"
    HCC_AMDGPU_TARGET: "gfx900"
test/intel:15:
  extends: .test_template_v40
  tags:
    - docker
    - linux
    - icp
test/intel:18:
  extends: .test_template
  tags:
    - docker
    - linux
    - icp
test/ubuntu-python3:16.04:
  extends: .test_py3_template
test/ubuntu-python3:18.04:
  extends: .test_py3_template
test/ubuntu-python3:min_boost:
  extends: .test_py3_template

centos:7:
  extends: .deploy_template
centos-python3:7:
  extends: .deploy_template
centos:next:
  extends: .deploy_template
centos-python3:next:
  extends: .deploy_template
debian:9:
  extends: .deploy_template
opensuse:42.3:
  extends: .deploy_template
opensuse:15.0:
  extends: .deploy_template
opensuse:15.1:
  extends: .deploy_template
ubuntu:16.04:
  extends: .deploy_template
ubuntu:summerschool:
  extends: .deploy_template
ubuntu:18.04:
  extends: .deploy_template
ubuntu:wo-dependencies:
  extends: .deploy_template
clang:6.0:
  extends: .deploy_template
cuda:tutorials:
  extends: .deploy_template
cuda:9.0:
  extends: .deploy_template
rocm:latest:
  extends: .deploy_template
intel:15:
  extends: .deploy_template
  tags:
    - docker
    - linux
    - nofirewall
    - icp
intel:18:
  extends: .deploy_template
  tags:
    - docker
    - linux
    - nofirewall
    - icp
ubuntu-python3:16.04:
  extends: .deploy_template
ubuntu-python3:18.04:
  extends: .deploy_template
ubuntu-python3:min_boost:
  extends: .deploy_template
ubuntu:arm64:
  extends: .deploy_template
ubuntu:armhf:
  extends: .deploy_template
ubuntu:i386:
  extends: .deploy_template
ubuntu:ppc64le:
  extends: .deploy_template
ubuntu:s390x:
  extends: .deploy_template

status_success:
  stage: status
  image: $CI_REGISTRY/espressomd/docker/ubuntu:18.04
  script: bash maintainer/gh_post_status.sh success
  when: on_success
  tags:
    - linux

status_failure:
  stage: status
  image: $CI_REGISTRY/espressomd/docker/ubuntu:18.04
  script: bash maintainer/gh_post_status.sh failure
  when: on_failure
  tags:
    - linux
