# action.yml
name: 'test-with-espresso'
description: 'test if ESPResSo can be build in given docker image'
inputs:
  image:
    description: 'docker image'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.image }}
